const ADMIN=window.__ADMIN__||{}, MY_PERMS=window.__PERMS__||{}; let admins=[],roles=[],stats={},week='';
const $=s=>document.querySelector(s); const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(url,method='GET',body){try{const o={method,headers:{Accept:'application/json'},credentials:'include'};if(body!==undefined){o.headers['Content-Type']='application/json';o.body=JSON.stringify(body)}const r=await fetch(url,o),t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{d={error:t||`HTTP ${r.status}`}}if(r.status===401){location='/login';return{error:'Не авторизован'}}if(!r.ok&&!d.error)d.error=`HTTP ${r.status}`;return d}catch(e){toast('Ошибка соединения',true);return{error:e.message}}}
function toast(m,bad=false){document.querySelector('.toast')?.remove();const x=document.createElement('div');x.className='toast'+(bad?' bad':'');x.textContent=m;document.body.append(x);setTimeout(()=>x.remove(),3500)}
function showPage(n){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+n));document.querySelectorAll('.navBtn').forEach(x=>x.classList.toggle('active',x.dataset.page===n));$('#sidebar')?.classList.remove('open');if(n==='me')loadMine();if(n==='admins')loadAdmins();if(n==='roles')loadRoles();if(n==='logs')loadLogs();if(n==='server')loadServer()}
function closeModal(id){$('#'+id)?.classList.remove('open')}
function fmtDate(v){return v?new Date(v).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—'}
function avatar(a){return a.discord_avatar||a.vk_avatar||''}
async function loadMine(){const d=await api('/api/admins/'+ADMIN.id);if(d.error)return;const a=d.admin;const img=document.querySelector('#page-me .profileAvatar');if(img&&avatar(a)){img.src=avatar(a);img.style.visibility='visible'}$('#myMessages').textContent=d.messages??0;$('#week').textContent=d.week?d.week.split(' ')[0]:'—';const s=await api('/api/status');if(!s.error)$('#myDiscordStatus').innerHTML=s.discord==='online'?'<span class="online">● Онлайн</span>':'<span class="offline">● Оффлайн</span>';$('#updated').textContent=s.bridgeUpdatedAt?fmtDate(s.bridgeUpdatedAt):'—';renderStatus('#status',s);renderTimeline('#myLogs',(d.logs||[]).slice(0,8))}
function renderStatus(sel,d){if(!d||d.error){$(sel).innerHTML='<div class="empty">Нет данных от бота</div>';return}const vals=[['Discord',d.discord],['VK',d.vk],['Telegram',d.telegram],['Anti-Sliv',d.antiSliv?'online':'offline'],['Ping',d.ping==null?'—':d.ping+' ms'],['Uptime',fmtUptime(d.uptime)]];$(sel).innerHTML=vals.map(([n,v])=>`<div class="stat"><small>${n}</small><b>${['online','offline'].includes(v)?(v==='online'?'<span class="online">● Онлайн</span>':'<span class="offline">● Оффлайн</span>'):esc(v)}</b></div>`).join('')}
function fmtUptime(s){s=Number(s)||0;const d=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60);return `${d?d+'д ':''}${h}ч ${m}м`}
async function loadAdmins(){const d=await api('/api/admins');if(d.error)return;admins=d.admins||[];stats=d.stats||{};week=d.week||'';renderAdmins()}
function renderAdmins(){const q=($('#adminSearch')?.value||'').toLowerCase();const arr=admins.filter(a=>`${a.nickname||''} ${a.discord_nickname||''} ${a.position||''} ${a.vk_id||''} ${a.discord_id||''}`.toLowerCase().includes(q));if(!arr.length){$('#admins').innerHTML='<div class="empty">Администраторы не найдены</div>';return}let h='<table class="table"><thead><tr><th>Администратор</th><th>Уровень</th><th>Роль</th><th>Сообщения</th><th>Действия</th></tr></thead><tbody>';for(const a of arr){const c=Number(stats[String(a.discord_id)]||0),canEdit=MY_PERMS.edit_admins&&Number(a.admin_level)<Number(ADMIN.level);h+=`<tr><td><div class="user"><img class="mini" src="${esc(avatar(a))}" onerror="this.style.visibility='hidden'"><div><b>${esc(a.nickname||a.discord_nickname||a.username)}</b><span>${esc(a.position||'Без должности')}</span></div></div></td><td><span class="badge">◈ ${a.admin_level}</span></td><td><span class="badge">${esc(a.role_name||'Без роли')}</span></td><td>${c}</td><td class="actions"><button class="btn" onclick="openProfile(${a.id})">Профиль</button>${canEdit?`<button class="btn" onclick="editAdmin(${a.id})">Изменить</button>`:''}${MY_PERMS.manage_admins&&Number(a.admin_level)<Number(ADMIN.level)?`<button class="btn danger" onclick="deleteAdmin(${a.id})">Удалить</button>`:''}</td></tr>`}h+='</tbody></table>';$('#admins').innerHTML=h}
async function openProfile(id){const d=await api('/api/admins/'+id);if(d.error)return toast(d.error,true);const a=d.admin;$('#profileTitle').textContent=a.nickname||a.discord_nickname||a.username;$('#profileBody').innerHTML=`<div class="profile"><img class="profileAvatar" src="${esc(avatar(a))}" onerror="this.style.visibility='hidden'"><div><h2>${esc(a.nickname||a.discord_nickname||a.username)}</h2><div class="position">${esc(a.position||'Без должности')}</div><div class="chips"><span class="chip">Уровень ${a.admin_level}</span><span class="chip">${esc(a.role_name||'Без роли')}</span><span class="chip">Discord: ${esc(a.discord_id)}</span><span class="chip">VK: ${esc(a.vk_id)}</span><span class="chip">${d.messages||0} сообщений за неделю</span></div></div></div><div class="section"><h3>Журнал изменений</h3><div class="timeline">${(d.logs||[]).map(e=>`<div class="event"><b>${esc(e.action)}</b><div>${esc(e.reason||'Без причины')}</div><small>${esc(e.actor_name||'Система')} · ${fmtDate(e.created_at)}</small></div>`).join('')||'<div class="empty">Изменений пока нет</div>'}</div></div><div class="actions">${MY_PERMS.edit_admins&&Number(a.admin_level)<Number(ADMIN.level)?`<button class="btn primary" onclick="closeModal('profileModal');editAdmin(${a.id})">Редактировать</button>`:''}${MY_PERMS.manage_admins&&Number(a.admin_level)<Number(ADMIN.level)?`<button class="btn danger" onclick="deleteAdmin(${a.id})">Удалить профиль</button>`:''}</div>`;$('#profileModal').classList.add('open')}
async function editAdmin(id){const d=await api('/api/admins/'+id);if(d.error)return toast(d.error,true);await loadRoles(true);const a=d.admin,f=$('#adminForm');f.id.value=a.id;f.username.value=a.username;f.password.value='';f.vk_id.value=a.vk_id||'';f.discord_id.value=a.discord_id||'';f.nickname.value=a.nickname||a.discord_nickname||'';f.position.value=a.position||'';f.admin_level.value=a.admin_level;f.role_id.value=a.role_id||'';f.reason.value='';$('#adminModalTitle').textContent='Редактирование: '+(a.nickname||a.username);$('#adminModal').classList.add('open')}
async function deleteAdmin(id){const reason=prompt('Причина удаления:');if(!reason)return;const d=await api('/api/admins/'+id,'DELETE',{reason});if(d.error)return toast(d.error,true);toast('Профиль удалён');closeModal('profileModal');loadAdmins()}
async function loadRoles(openEditor=false){if(!MY_PERMS.manage_roles)return;const d=await api('/api/roles');if(d.error)return;roles=d||[];const render=rows=>{let h='';for(const r of rows){h+=`<div class="card" style="margin:10px 0"><div class="head"><div><h3>${esc(r.name)}</h3><span class="muted">${r.permissions.length} прав</span></div><div class="actions"><button class="btn" onclick="editRole(${r.id})">Изменить</button><button class="btn danger" onclick="deleteRole(${r.id})">Удалить</button></div></div><div class="chips">${r.permissions.map(p=>`<span class="badge">${esc(p)}</span>`).join('')}</div></div>`}return h||'<div class="empty">Ролей нет</div>'};$('#roles').innerHTML=`<div class="head"><div><h2>Роли</h2><span class="muted">У роли нет уровня — только набор разрешений.</span></div><button class="btn primary" onclick="createRole()">＋ Создать роль</button></div><div style="margin-top:15px">${render(roles)}</div>`;populateRoleSelects()}
async function populateRoleSelects(){const opts='<option value="">Без роли</option>'+roles.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('');$('#adminRole').innerHTML=opts;$('#createRole').innerHTML=opts}
async function createRole(){if(!MY_PERMS.manage_roles)return;const f=$('#roleForm');f.reset();f.id.value='';$('#roleTitle').textContent='Создать роль';renderPerms([]);$('#roleModal').classList.add('open')}
async function editRole(id){const r=roles.find(x=>x.id==id);if(!r)return;const f=$('#roleForm');f.id.value=r.id;f.name.value=r.name;f.reason.value='';renderPerms(r.permissions);$('#roleTitle').textContent='Редактировать роль';$('#roleModal').classList.add('open')}
function renderPerms(selected){const all=[['view_status','Просмотр статуса'],['view_stats','Просмотр статистики'],['manage_admins','Создание/удаление админов'],['edit_admins','Редактирование админов'],['manage_roles','Управление ролями'],['view_logs','Просмотр журналов'],['manage_settings','Настройки бота']];$('#permissionList').innerHTML=all.map(([id,n])=>`<label class="permission"><input type="checkbox" name="perm" value="${id}" ${selected.includes(id)?'checked':''}>${n}</label>`).join('')}
async function saveRole(e){e.preventDefault();const f=new FormData(e.target),id=f.get('id'),permissions=[...document.querySelectorAll('#permissionList input:checked')].map(x=>x.value),body={name:f.get('name'),permissions,reason:f.get('reason')};const d=await api(id?'/api/roles/'+id:'/api/roles',id?'PATCH':'POST',body);if(d.error)return toast(d.error,true);toast(id?'Роль изменена':'Роль создана');closeModal('roleModal');loadRoles()}
async function deleteRole(id){const reason=prompt('Причина удаления роли:');if(!reason)return;const d=await api('/api/roles/'+id,'DELETE',{reason});if(d.error)return toast(d.error,true);toast('Роль удалена');loadRoles()}
async function loadLogs(){if(!MY_PERMS.view_logs){$('#logs').innerHTML='<div class="empty">Нет права просмотра журнала</div>';return}const d=await api('/api/logs');if(d.error)return;renderTimeline('#logs',d)}
function renderTimeline(sel,rows){$(sel).innerHTML=(rows||[]).map(e=>`<div class="event"><b>${esc(e.action)}</b><div>${esc(e.reason||'')}</div><small>${esc(e.actor_name||'Система')} · ${fmtDate(e.created_at)}</small></div>`).join('')||'<div class="empty">Журнал пуст</div>'}
async function loadServer(){const s=await api('/api/status'),d=await api('/api/stats');renderStatus('#serverStatus',s);if(d.error){$('#serverStats').innerHTML='<div class="empty">Статистика недоступна</div>';return}const g=d.guild||{},at=d.attempts||{};const items=[['Участники',g.members||0],['Люди',g.humans||0],['Боты',g.bots||0],['Онлайн',g.online||0],['Каналы',g.channels||0],['Роли',g.roles||0],['Бусты',g.boosts||0],['Anti-Sliv сегодня',at.total||0],['Заблокировано',at.reached||0],['Сообщений админов',Object.values(d.adminMessages||{}).reduce((a,b)=>a+Number(b||0),0)]];$('#serverStats').innerHTML=items.map(x=>`<div class="stat"><small>${x[0]}</small><b>${esc(x[1])}</b></div>`).join('')}
$('#menu')?.addEventListener('click',()=>$('#sidebar').classList.toggle('open'));document.querySelectorAll('.navBtn').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));$('.sideUser')?.addEventListener('click',()=>showPage('me'));$('#refresh')?.addEventListener('click',loadMine);$('#serverRefresh')?.addEventListener('click',loadServer);$('#adminSearch')?.addEventListener('input',renderAdmins);$('#addAdmin')?.addEventListener('click',async()=>{await loadRoles();$('#createForm').reset();$('#createModal').classList.add('open')});$('#createForm')?.addEventListener('submit',async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));body.admin_level=Number(body.admin_level);body.role_id=body.role_id?Number(body.role_id):null;const d=await api('/api/admins','POST',body);if(d.error)return toast(d.error,true);toast('Администратор создан');closeModal('createModal');e.target.reset();loadAdmins()});$('#adminForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),id=f.get('id');const body=Object.fromEntries(f);body.admin_level=Number(body.admin_level);body.role_id=body.role_id?Number(body.role_id):null;const d=await api('/api/admins/'+id,'PATCH',body);if(d.error)return toast(d.error,true);toast('Профиль обновлён');closeModal('adminModal');loadAdmins()});$('#roleForm')?.addEventListener('submit',saveRole);document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));loadMine();
window.openProfile=openProfile;window.editAdmin=editAdmin;window.deleteAdmin=deleteAdmin;window.editRole=editRole;window.createRole=createRole;window.deleteRole=deleteRole;window.closeModal=closeModal;
